<a href="https://colab.research.google.com/github/youcine/ML_and_DL_applications_in_health/blob/main/Regression_%7C_Drug_Design_anti_leshmania_%7C_ANN%2C_MLP%2C_Deep_Learning_Applications.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Access to google drive***

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd /content/drive/MyDrive/ENSB Atelier

/content/drive/MyDrive/ENSB Atelier


In [ ]:
ls

baggingmodel  DragonMSI-IC50-All.txt


# ***Get DATAFRAME ('Tableau') from file using pandas where file is csv format***

In [ ]:
import pandas as pd
data = pd.read_csv('DragonMSI-IC50-All.txt',delimiter='\t')

In [ ]:
print(data)

    No.         MolID     pIC50  pIC50-95  pIC50-96  pIC50-97  pIC50-98  \
0     1   C47H73N1O17 -0.133539 -0.071882 -0.071882 -1.000868 -0.962843   
1     2  C21H46N1O4P1 -1.016197 -0.806180 -0.806180 -1.651084 -1.609167   
2     3      C10H12O2 -2.645088 -2.238698 -2.238698 -2.721844 -2.677388   
3     4      C12H14O3 -2.219899 -1.996117 -1.996117 -2.551560 -2.546802   
4     5      C11H14O2 -2.677105 -2.308095 -2.308095 -2.713843 -2.685787   
5     6    C17H15O3F1 -1.787177 -1.894371 -1.894371 -2.560922 -2.602060   
6     7   C17H15O3Cl1 -1.809425 -1.762978 -1.762978 -2.399847 -2.439348   
7     8      C14H20O2 -2.489860 -2.167760 -2.167760 -2.516760 -2.537895   
8     9      C13H18O2 -2.124080 -2.192317 -2.192317 -2.041551 -2.044226   
9    10      C12H16O2 -1.855337 -2.209863 -2.209863 -2.007705 -1.956649   
10   11      C13H16O2 -2.375810 -2.080193 -2.080193 -2.585212 -2.548217   
11   12      C18H18O3 -1.523226 -0.967548 -0.967548 -2.592510 -2.585900   
12   13    C16H21N1O3 -1.

# ***Show the loaded data in table format***

In [ ]:
data.head()

No.         MolID     pIC50  pIC50-95  pIC50-96  pIC50-97  pIC50-98  \
0    1   C47H73N1O17 -0.133539 -0.071882 -0.071882 -1.000868 -0.962843   
1    2  C21H46N1O4P1 -1.016197 -0.806180 -0.806180 -1.651084 -1.609167   
2    3      C10H12O2 -2.645088 -2.238698 -2.238698 -2.721844 -2.677388   
3    4      C12H14O3 -2.219899 -1.996117 -1.996117 -2.551560 -2.546802   
4    5      C11H14O2 -2.677105 -2.308095 -2.308095 -2.713843 -2.685787   

   pIC50-99  pIC50-100      MW  ...  Psychotic-80  Hypertens-80  Hypnotic-80  \
0 -0.869232  -0.890980  924.21  ...             0             0            0   
1 -0.633468  -0.802089  407.65  ...             0             0            0   
2 -0.075547  -0.439333  164.22  ...             0             0            1   
3 -0.332438  -0.555094  206.26  ...             0             1            1   
4 -0.037426  -0.378398  178.25  ...             0             0            1   

   Neoplastic-80  Neoplastic-50  Infective-80  Infective-50  BLTF96  BLTD48  \
0              0              0             0             0   -0.53   -0.36   
1              0              0             0             0   -2.21   -2.24   
2              0              0             1             0   -3.18   -3.32   
3              1              0             1             0   -3.58   -3.76   
4              0              0             1             0   -3.43   -3.60   

   BLTA96  
0   -0.21  
1   -2.20  
2   -3.34  
3   -3.80  
4   -3.63  

[5 rows x 647 columns]

# ***Load using .iloc[rows,columns] the targeted columns and rows, and convert it to vectors using .values***

In [ ]:
x = data.iloc[:,9:]

In [ ]:
print(x)

        MW   AMW     Sv      Se     Sp      Ss    Mv    Me    Mp    Ms  ...  \
0   924.21  6.70  78.22  139.48  83.14  174.58  0.57  1.01  0.60  2.69  ...   
1   407.65  5.58  38.67   71.71  43.02   56.81  0.53  0.98  0.59  2.10  ...   
2   164.22  6.84  14.61   23.96  15.48   29.00  0.61  1.00  0.64  2.42  ...   
3   206.26  7.11  17.72   29.17  18.69   37.17  0.61  1.01  0.64  2.48  ...   
4   178.25  6.60  16.21   26.84  17.24   28.50  0.60  0.99  0.64  2.19  ...   
5   286.32  7.95  23.43   36.56  24.39   54.50  0.65  1.02  0.68  2.60  ...   
6   302.77  8.41  24.02   36.37  25.31   50.61  0.67  1.01  0.70  2.41  ...   
7   220.34  6.12  21.00   35.49  22.52   33.00  0.58  0.99  0.63  2.06  ...   
8   206.31  6.25  19.40   32.61  20.76   31.50  0.59  0.99  0.63  2.10  ...   
9   192.28  6.41  17.81   29.72  19.00   30.00  0.59  0.99  0.63  2.14  ...   
10  204.29  6.59  18.81   30.72  20.00   33.00  0.61  0.99  0.65  2.20  ...   
11  282.36  7.24  24.92   38.93  26.22   48.33  0.64

In [ ]:
y = data.iloc[:,2]

In [ ]:
print(y)

0    -0.133539
1    -1.016197
2    -2.645088
3    -2.219899
4    -2.677105
5    -1.787177
6    -1.809425
7    -2.489860
8    -2.124080
9    -1.855337
10   -2.375810
11   -1.523226
12   -1.949439
13   -2.163817
14   -2.383959
15   -1.720242
16   -1.460296
17   -1.781396
18   -2.026574
19   -1.303844
20   -2.209515
21   -1.636187
22   -1.763802
23   -1.749427
24   -1.904607
25   -1.794488
26   -1.828982
27   -1.787602
28   -1.779885
29   -1.698275
30   -1.988336
31   -1.971369
32   -1.809223
33   -1.724030
34   -1.915822
35   -1.885700
36   -1.958134
37   -2.013974
38   -1.834548
39   -1.913496
Name: pIC50, dtype: float64


# ***Data processing***

# **Normalization **

In [ ]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler object
scaler = StandardScaler()

# Transform the data
x = scaler.fit_transform(x)

# ***Construire l'ensemble de teste et l'ensemble d'apprentissage***

In [ ]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42,shuffle=True)

# ***Training the ANN model***

In [ ]:
import tensorflow as tf
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(638,))
model.add(tf.keras.layers.Dropout(0.6))
model.add(tf.keras.layers.Dense(1,activation='linear'))
model.compile(loss='mse',optimizer='ADAM')
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dropout_1 (Dropout)         (None, 638)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 639       
                                                                 
Total params: 639
Trainable params: 639
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train,y_train,epochs=500,batch_size=40)

Epoch 1/500
1/1 [==============================] - 0s 344ms/step - loss: 18.3760
Epoch 2/500
1/1 [==============================] - 0s 8ms/step - loss: 7.3968
Epoch 3/500
1/1 [==============================] - 0s 7ms/step - loss: 8.8104
Epoch 4/500
1/1 [==============================] - 0s 7ms/step - loss: 5.2457
Epoch 5/500
1/1 [==============================] - 0s 8ms/step - loss: 14.8867
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 6.3857
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 7.8362
Epoch 8/500
1/1 [==============================] - 0s 6ms/step - loss: 8.2966
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 7.3619
Epoch 10/500
1/1 [==============================] - 0s 6ms/step - loss: 4.2829
Epoch 11/500
1/1 [==============================] - 0s 5ms/step - loss: 9.5310
Epoch 12/500
1/1 [==============================] - 0s 7ms/step - loss: 6.9042
Epoch 13/500
1/1 [==============================] - 0s 5m

In [ ]:
print(X_test.shape)

(8, 638)


# ***Evaluation du modèle en utilisant la partie Teste***

In [ ]:
model.evaluate(X_test,y_test)

1/1 [==============================] - 0s 71ms/step - loss: 2.6152


2.6152167320251465

# *** Modéle MLP***

In [ ]:
pip install tensorflow-addons

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 44.8 MB/s eta 0:00:00


In [ ]:
import tensorflow as tf
from tensorflow_addons.metrics import RSquare
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(638,))
model.add(tf.keras.layers.Dense(1024,activation='relu'))
model.add(tf.keras.layers.Dropout(0.6))
model.add(tf.keras.layers.Dense(1,activation='linear'))
model.compile(loss='mse',optimizer='ADAM',metrics=['mae',RSquare()])
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 1024)              654336    
                                                                 
 dropout_8 (Dropout)         (None, 1024)              0         
                                                                 
 dense_16 (Dense)            (None, 1)                 1025      
                                                                 
Total params: 655,361
Trainable params: 655,361
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train,y_train,epochs=100)


Epoch 1/100
1/1 [==============================] - 0s 16ms/step - loss: 1.3359 - mae: 0.8250 - r_square: -9.3004
Epoch 2/100
1/1 [==============================] - 0s 18ms/step - loss: 1.7603 - mae: 0.9542 - r_square: -12.0292
Epoch 3/100
1/1 [==============================] - 0s 16ms/step - loss: 3.1721 - mae: 1.0152 - r_square: -22.9764
Epoch 4/100
1/1 [==============================] - 0s 16ms/step - loss: 1.6109 - mae: 0.9321 - r_square: -11.0241
Epoch 5/100
1/1 [==============================] - 0s 14ms/step - loss: 0.8343 - mae: 0.7379 - r_square: -6.0375
Epoch 6/100
1/1 [==============================] - 0s 14ms/step - loss: 0.8749 - mae: 0.7676 - r_square: -6.1234
Epoch 7/100
1/1 [==============================] - 0s 16ms/step - loss: 1.2532 - mae: 0.8470 - r_square: -8.7645
Epoch 8/100
1/1 [==============================] - 0s 17ms/step - loss: 1.3133 - mae: 0.8669 - r_square: -9.1436
Epoch 9/100
1/1 [==============================] - 0s 17ms/step - loss: 3.7508 - mae: 1.0283 

In [ ]:
model.evaluate(X_test,y_test)

1/1 [==============================] - 0s 117ms/step - loss: 0.6706 - mae: 0.6834 - r_square: -16.5908


[0.6705705523490906, 0.6833670139312744, -16.5908260345459]

In [ ]:
print(model.predict(X_test))

1/1 [==============================] - 0s 158ms/step
[[-1.7142619  -1.2723391  -1.1031184  -2.712898   -2.6795568  -0.9252762 ]
 [-2.1261344  -1.7731365  -1.5923777  -3.4780552  -3.0494504  -1.6339802 ]
 [-1.7896069  -1.4843228  -1.3214707  -2.5514708  -2.441423   -0.83018804]
 [-1.8238069  -1.5501617  -1.523329   -2.6990945  -2.6811225  -0.84229565]
 [-2.533948   -2.3852832  -2.244584   -2.5864034  -2.4574158  -0.22287491]
 [-1.7852987  -1.9961373  -2.170886   -2.4826474  -2.503213   -0.24269854]
 [-2.3802729  -2.0467424  -2.110205   -2.9651883  -3.079026   -0.72994965]
 [-2.2542624  -2.1557012  -2.08003    -2.6326857  -2.7354841  -0.7703866 ]]


# ***Modéle Convolutional Neural Network***

In [ ]:
import tensorflow as tf
from tensorflow_addons.metrics import RSquare
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(638,))
model.add(tf.keras.layers.Reshape((638,1)))
model.add(tf.keras.layers.Conv1D(32,kernel_size=100,activation='relu'))
model.add(tf.keras.layers.MaxPool1D(pool_size=5))
model.add(tf.keras.layers.Dropout(0.6))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(1,activation='linear'))
model.compile(loss='mse',optimizer='ADAM',metrics=['mae',RSquare()])
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape_4 (Reshape)         (None, 638, 1)            0         
                                                                 
 conv1d_5 (Conv1D)           (None, 539, 32)           3232      
                                                                 
 max_pooling1d_2 (MaxPooling  (None, 5, 32)            0         
 1D)                                                             
                                                                 
 dropout_13 (Dropout)        (None, 5, 32)             0         
                                                                 
 flatten_3 (Flatten)         (None, 160)               0         
                                                                 
 dense_21 (Dense)            (None, 1)                 161       
                                                     

In [ ]:
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 385ms/step - loss: 2.8411 - mae: 1.4727 - r_square: -14.1810
Epoch 2/100
1/1 [==============================] - 0s 25ms/step - loss: 2.5682 - mae: 1.4089 - r_square: -12.7230
Epoch 3/100
1/1 [==============================] - 0s 25ms/step - loss: 1.5187 - mae: 1.0725 - r_square: -7.1147
Epoch 4/100
1/1 [==============================] - 0s 24ms/step - loss: 1.7749 - mae: 1.1804 - r_square: -8.4838
Epoch 5/100
1/1 [==============================] - 0s 21ms/step - loss: 2.0318 - mae: 1.2725 - r_square: -9.8567
Epoch 6/100
1/1 [==============================] - 0s 21ms/step - loss: 2.0527 - mae: 1.2230 - r_square: -9.9684
Epoch 7/100
1/1 [==============================] - 0s 22ms/step - loss: 1.3206 - mae: 0.9667 - r_square: -6.0563
Epoch 8/100
1/1 [==============================] - 0s 22ms/step - loss: 1.5673 - mae: 0.9448 - r_square: -7.3745
Epoch 9/100
1/1 [==============================] - 0s 22ms/step - loss: 1.7342 - mae: 0.9231 

In [ ]:
model.evaluate(X_test,y_test)

1/1 [==============================] - 0s 134ms/step - loss: 0.1450 - mae: 0.3290 - r_square: 0.0267


[0.14499036967754364, 0.3290347158908844, 0.026727616786956787]